"""Initial migration

Revision ID: 663af4d44077
Revises: 
Create Date: 2024-09-03 22:52:58.061047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663af4d44077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia_operacji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ_operacji', sa.String(length=50), nullable=False),
    sa.Column('opis', sa.String(length=200), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('konto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produkt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=100), nullable=False),
    sa.Column('cena', sa.Integer(), nullable=False),
    sa.Column('ilosc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produkt')
    op.drop_table('konto')
    op.drop_table('historia_operacji')
    # ### end Alembic commands ###
